//package com.ridesigncommunity.RiDesignCommunity.service;
//
//import static org.junit.jupiter.api.Assertions.*;
//import static org.mockito.Mockito.*;
//
//import com.ridesigncommunity.RiDesignCommunity.dto.ProductDto;
//import com.ridesigncommunity.RiDesignCommunity.model.Product;
//import com.ridesigncommunity.RiDesignCommunity.repository.ProductRepository;
//import org.junit.jupiter.api.*;
//import org.junit.jupiter.api.extension.ExtendWith;
//import org.mockito.*;
//import org.mockito.junit.jupiter.MockitoExtension;
//import org.springframework.security.crypto.password.PasswordEncoder;
//
//import java.util.ArrayList;
//import java.util.Collections;
//import java.util.Optional;
//
//@ExtendWith(MockitoExtension.class)
//public class ProductServiceTest {
//
//    @Mock
//    private ProductRepository productRepositoryMock;
//
//    @InjectMocks
//    private ProductService productService;
//
//    @BeforeEach
//    public void setUp() {
//        Mockito.reset(productRepositoryMock);
//    }
//
//    @Test
//    public void testCreateProduct_Success() {
//        // Arrange
//        ProductDto productDto = new ProductDto();
//        productDto.setProductTitle("Lounge Table Set cozy");
//        productDto.setCategory("Tafels");
//        productDto.setMeasurements("100x50x60 cm");
//        productDto.setMaterials("Hout, staal");
//        productDto.setDescription("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum sagittis nisi, eu consectetur velit. Cras nec nunc eget arcu dictum vulputate. Proin aliquet quam quis magna consequat, ac blandit eros finibus. Nam auctor vestibulum velit, nec mattis enim venenatis et. Duis eget feugiat elit.");
//        productDto.setPrice(139.99);
//        productDto.setDeliveryOptions(Collections.singletonList("Bezorgen"));
//
//        Product expectedProduct = new Product();
//        expectedProduct.setProductId(1L); // Assuming the ID generated by the repository
//        expectedProduct.setProductTitle("Sample Product");
//        expectedProduct.setCategory("Sample Category");
//        expectedProduct.setMeasurements("Sample Measurements");
//        expectedProduct.setMaterials("Sample Materials");
//        expectedProduct.setDescription("Sample Description");
//        expectedProduct.setPrice(100.0);
////        expectedProduct.setDeliveryOptions("Sample Delivery Options");
//
//        when(productRepositoryMock.save(any(Product.class))).thenReturn(expectedProduct);
//
//        // Act
////        Product createdProduct = productService.createProduct(productDto);
//
//        // Assert
//        assertNotNull(createdProduct);
//        assertEquals(expectedProduct.getProductId(), createdProduct.getProductId());
//        assertEquals(expectedProduct.getProductTitle(), createdProduct.getProductTitle());
//        assertEquals(expectedProduct.getCategory(), createdProduct.getCategory());
//        assertEquals(expectedProduct.getMeasurements(), createdProduct.getMeasurements());
//        assertEquals(expectedProduct.getMaterials(), createdProduct.getMaterials());
//        assertEquals(expectedProduct.getDescription(), createdProduct.getDescription());
//        assertEquals(expectedProduct.getPrice(), createdProduct.getPrice());
//        assertEquals(expectedProduct.getDeliveryOptions(), createdProduct.getDeliveryOptions());
//
//        // Verify that the repository's save method was called
//        verify(productRepositoryMock, times(1)).save(any(Product.class));
//    }
//
//}
